# VR Gaming Server - Enterprise Server Configuration
# Vollständige Enterprise-Konfiguration für professionelle VR-Streaming-Server

# Enterprise Server-Konfiguration
server:
  host: "0.0.0.0"
  port: 8080
  debug: false
  environment: "production"
  instance_id: "vr-gaming-server-01"
  cluster_mode: false
  load_balancer: false
  auto_restart: true
  graceful_shutdown_timeout: 30
  pid_file: "/var/run/vr-gaming-server.pid"
  user: "vrgaming"
  group: "vrgaming"

# Advanced Video-Konfiguration für 8K VR
video:
  width: 7680    # 8K Breite (4K pro Auge)
  height: 4320   # 8K Höhe
  fps: 120       # Extreme Framerate
  quality: 95
  codec: "h265"  # H.265 für bessere Kompression
  bitrate: 100000000  # 100 Mbps für 8K
  keyframe_interval: 2
  b_frames: 2
  preset: "ultrafast"
  tune: "zerolatency"
  profile: "main10"
  level: "6.2"
  color_space: "bt2020"
  hdr_support: true
  dolby_vision: true
  adaptive_resolution: true
  variable_fps: true
  frame_dropping: false

# Advanced Capture-Konfiguration
capture:
  method: "auto"
  monitor: 0
  target_window: null
  capture_api: "desktop_duplication"  # Windows
  capture_region: "fullscreen"
  cursor_capture: true
  cursor_scaling: true
  multi_monitor_support: true
  hdr_capture: true
  color_accuracy: "high"
  capture_buffering: true
  capture_threads: 4
  gpu_acceleration: true
  direct_capture: true

# Enterprise Input-Konfiguration
input:
  mouse_sensitivity: 1.0
  acceleration_curve: 1.0
  min_mouse_delta: 0.5
  keyboard_layout: "auto"
  input_buffering: true
  input_prediction: true
  anti_aliasing: true
  deadzone_compensation: true
  force_feedback: true
  haptic_feedback: true

# Advanced Head-Tracking mit 6DoF
head_tracking:
  enabled: true
  sensitivity_x: 1.0
  sensitivity_y: 1.0
  sensitivity_z: 1.0
  deadzone: 0.8
  smoothing: 0.15
  max_speed: 180.0
  invert_x: false
  invert_y: false
  invert_z: false
  prediction: true
  drift_compensation: true
  calibration_auto: true
  imu_fusion: true
  optical_tracking: true
  magnetic_compensation: true
  temperature_calibration: true

# Enterprise Streaming-Konfiguration
streaming:
  enable_webrtc: true
  enable_rtmp: true
  enable_hls: true
  enable_dash: true
  enable_srt: true
  mjpeg_quality: 95
  mjpeg_fps: 60
  adaptive_quality: true
  simulcast: true
  svc_layers: 3
  fec_enabled: true
  nack_enabled: true
  bandwidth_estimation: "gcc"
  jitter_buffer: 500
  latency_target: 50  # ms für VR

# Advanced Logging und Monitoring
logging:
  level: "INFO"
  file: "logs/server.log"
  max_file_size: "100MB"
  max_files: 10
  format: "json"
  syslog_enabled: true
  remote_logging: false
  log_rotation: "daily"
  compression: "gzip"

# Performance Monitoring
performance:
  monitoring_enabled: true
  metrics_interval: 1
  cpu_monitoring: true
  memory_monitoring: true
  gpu_monitoring: true
  network_monitoring: true
  disk_monitoring: true
  latency_monitoring: true
  fps_monitoring: true
  bandwidth_monitoring: true
  prometheus_export: true
  grafana_integration: true

# Security Konfiguration
security:
  authentication: "oauth2"
  authorization: "rbac"
  encryption: "tls1.3"
  certificate_path: "/etc/ssl/certs/"
  private_key_path: "/etc/ssl/private/"
  ca_certificate: "/etc/ssl/certs/ca.crt"
  jwt_secret: "change-this-in-production"
  session_timeout: 3600
  rate_limiting: true
  ip_whitelist: []
  geo_blocking: false
  audit_logging: true

# Database Konfiguration
database:
  type: "postgresql"
  host: "localhost"
  port: 5432
  database: "vr_gaming_server"
  username: "vrgaming"
  password: "change-this-in-production"
  ssl_mode: "require"
  connection_pool_size: 20
  connection_timeout: 30
  migrations_enabled: true

# Cache Konfiguration
cache:
  enabled: true
  type: "redis"
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  ttl: 3600
  compression: true
  cluster_mode: false

# Enterprise Features
enterprise:
  high_availability: true
  auto_scaling: true
  backup_enabled: true
  disaster_recovery: true
  compliance_mode: "gdpr"
  audit_trail: true
  multi_tenant: false
  api_rate_limiting: true
  custom_branding: false

# Cloud Integration
cloud:
  provider: "auto"  # aws, azure, gcp, none
  region: "us-east-1"
  availability_zone: "us-east-1a"
  instance_type: "c5.9xlarge"
  storage_bucket: "vr-gaming-server-backups"
  cdn_enabled: true
  load_balancer: "application"

# GPU Konfiguration
gpu:
  enabled: true
  device: "auto"
  memory_limit: "8GB"
  compute_mode: "exclusive_process"
  persistence_mode: true
  power_management: "performance"
  clock_speed: "maximum"
  fan_speed: "auto"

# Network Optimizations
network:
  tcp_optimization: true
  udp_optimization: true
  buffer_sizes: "4MB"
  congestion_control: "bbr"
  qos_enabled: true
  dscp_marking: 46
  jumbo_frames: true

# System Integration
system:
  systemd_service: true
  logrotate_config: true
  cron_jobs: true
  firewall_rules: true
  selinux_policy: true
  apparmor_profile: true

# API Konfiguration
api:
  enabled: true
  version: "v1"
  documentation: true
  swagger_ui: true
  rate_limiting: true
  cors_enabled: true
  authentication: "bearer"
  pagination: true
  filtering: true
  sorting: true

# Web Interface
web:
  enabled: true
  theme: "dark"
  language: "en"
  timezone: "UTC"
  session_timeout: 3600
  max_upload_size: "100MB"
  static_cache: true
  compression: true

# Backup Konfiguration
backup:
  enabled: true
  schedule: "daily"
  retention: 30
  compression: "gzip"
  encryption: true
  remote_storage: true
  verify_backups: true

# Alerting
alerting:
  enabled: true
  email_enabled: true
  sms_enabled: false
  slack_enabled: false
  pagerduty_enabled: false
  alert_rules:
    - name: "high_cpu"
      threshold: 90
      duration: 300
    - name: "high_memory"
      threshold: 90
      duration: 300
    - name: "low_fps"
      threshold: 30
      duration: 60
